---
title: "Larynx cancer in Germany: solution"
author: "Matteo Fasiolo"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    number_sections: true
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteIndexEntry{Larinx}
  %\VignetteEncoding{UTF-8}
---
  
```{r setup, include=FALSE}
library(knitr)
library(rgl)
opts_chunk$set(out.extra='style="display:block; margin: auto"', fig.align="center", tidy=FALSE)
knit_hooks$set(webgl = hook_webgl)
```

```{r setup1, include=FALSE}
# Set workdir to source file location and then
library(RhpcBLASctl); blas_set_num_threads(1)
```

1) Load data and fit a Poisson GAM with MRF smooth:
```{r lary1, message = F}
library(testGam)
library(mgcViz)
data("Larynx")
data("german.polys")

X <- t(sapply(german.polys,colMeans,na.rm=TRUE))

fit1 <- gamV(Y ~ s(region, k = 200, bs="mrf",xt=list(polys=german.polys)) + offset(log(E)) + s(x, k=20),
             family=poisson, data=Larynx, aViz = list(nsim = 50))

print(plot(fit1), ask = FALSE)
```

2) Now use isotropic TPS smooth:
```{r lary2, message = F}
fit2 <- gamV(Y~s(X[,1],X[,2],k=200)+offset(log(E))+s(x,k=20), family=poisson, data=Larynx)

print(plot(fit2, select = 1), ask = FALSE)
```

Now use tensor-product smooth:
```{r lary3, message = F}
fit3 <- gamV(Y~te(X[,1],X[,2],k=c(15, 15))+offset(log(E))+s(x,k=20), family=poisson, data=Larynx)

print(plot(fit3, select = 1), ask = FALSE)

AIC(fit1, fit2, fit3)
```
MRF model is better in terms of AIC.

3) Now visualize effect using rgl:
```{r lary4, message = F, webgl=TRUE}
open3d()
mfrow3d(1, 2)
plotRGL(sm(fit2,1), residuals = TRUE)
next3d()
plotRGL(sm(fit3,1), residuals = TRUE)
```
Tensor effect seems smoother.
